/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos_timesquare.view;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Calendar;
import java.util.HashMap;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import pos_timesquare.controller.CustomerService;
import pos_timesquare.model.Customer;
import pos_timesquare.utils.RingChartCustomer;
import pos_timesquare.utils.WrapLayout;
import static pos_timesquare.view.MainFrame.createCustomerDialog;
import static pos_timesquare.view.MainFrame.darkRB;
import static pos_timesquare.view.MainFrame.jButton39;
import static pos_timesquare.view.MainFrame.jLabel309;
import static pos_timesquare.view.MainFrame.jPanel226;
import static pos_timesquare.view.MainFrame.jPanel64;
import static pos_timesquare.view.MainFrame.jTextField1;
import static pos_timesquare.view.MainFrame.selectedFile;
import static pos_timesquare.view.MainFrame.serviceCustomer;
import static pos_timesquare.view.MainFrame.totalNewCustomer;
import static pos_timesquare.view.MainFrame.totalRegisteredCustomer;
import static pos_timesquare.view.MainFrame.updateGraphics;

/**
 *
 * @author Acer
 */
public class CreateNewCustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewCustomerPanel
     */
    
    File selectedFile;
    
    boolean isCustomerService = false;
    public void isForCustomerService(boolean value){
        isCustomerService = value;
    }
    
    public CreateNewCustomerPanel() {
        initComponents();
        jRadioButton3.setActionCommand("male");
        jRadioButton4.setActionCommand("female");
        
        buttonGroup1.add(jRadioButton4);
        buttonGroup1.add(jRadioButton3);
        
        jRadioButton3.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jPanel20 =
        new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g.create();

                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                if(darkRB.isSelected()){
                    g2.setColor(new Color(38, 41, 48));
                }else{
                    g2.setColor(new Color(255, 255, 255));
                }
                g2.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 25, 25);
            }

        };
        jLabel61 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField26 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jButton40 = new javax.swing.JButton();
        jLabel14 = new JLabel(){
            public void paintComponent(Graphics g){
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g.create();

                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                if(darkRB.isSelected()){
                    g2.setColor(new Color(38, 41, 48));
                }else{
                    g2.setColor(new Color(255, 255, 255));
                }
                for(int i = 24; i >= 0; i--){
                    g2.drawRoundRect(0, 0, this.getWidth()-1, this.getHeight()-1, i, i);
                }
                //            g2.setColor(Color.GRAY);
                if(darkRB.isSelected()){
                    g2.setColor(new Color(58, 61, 68));
                }else{
                    g2.setColor(new Color(225, 225, 225));
                }
                g2.setStroke(new BasicStroke(2));
                g2.drawRoundRect(0, 0, this.getWidth()-1, this.getHeight()-1, 25, 25);

                //            if(isHover){
                    //                g2.setColor(new Color(0,144,228));
                    //                g2.setStroke(new BasicStroke(1));
                    //                g2.drawRoundRect(0, 0, this.getWidth()-1, this.getHeight()-1, 25, 25);
                    //            }
            }
        };

        setMinimumSize(new java.awt.Dimension(621, 490));
        setPreferredSize(new java.awt.Dimension(621, 500));

        jButton6.setText("Add Image");
        jButton6.setPreferredSize(new java.awt.Dimension(75, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel62.setText("Create New Customer");

        jPanel20.setMinimumSize(new java.awt.Dimension(267, 407));
        jPanel20.setOpaque(false);

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel61.setText("Name");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Address");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Birth Date");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Birth Date");

        jRadioButton3.setText("Male");

        jRadioButton4.setText("Female");

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setText("Contact No.");

        jButton40.setBackground(new java.awt.Color(0, 144, 228));
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setText("Confirm");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel54)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4))
                    .addComponent(jLabel26)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jButton40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField26)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4)
                    .addComponent(jLabel61)
                    .addComponent(jTextField27, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(9, 9, 9)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel62)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
        
        
        File file = selectedFile;
            if (file != null) {
                String filename = file.getAbsolutePath();
                
                InputStream inStream = null;
                OutputStream outStream = null;
                try {
                    File source = new File(filename);
                    File dest = new File(System.getProperty("user.dir") + "/img/profile/", file.getName());
                    inStream = new FileInputStream(source);
                    outStream = new FileOutputStream(dest);
                    
                    byte[] buffer = new byte[1024];
                    
                    int length;
                    while ((length = inStream.read(buffer)) > 0) {
                        outStream.write(buffer, 0, length);
                    }
                    
                    if (inStream != null) {
                        inStream.close();
                    }
                    if (outStream != null) {
                        outStream.close();
                    }
                    System.out.println("File Copied..");
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        
        CustomerService cs = new CustomerService();
        Customer customer = new Customer();
        
        customer.setName(jTextField27.getText());
        customer.setAddress(jTextField4.getText());
        customer.setBirthDate(new java.sql.Timestamp(jDateChooser3.getDate().getTime()).toString());
        customer.setContactNum(jTextField26.getText());
        customer.setGender(buttonGroup1.getSelection().getActionCommand());
        
        if(file != null){
            customer.setImage("/img/profile/" + file.getName());
        }
        
//        customer.setImage();
        customer.setMembershipDate(new java.sql.Timestamp(Calendar.getInstance().getTime().getTime()).toString());
        customer.setStatus("Active");
        
        System.out.println(new java.sql.Timestamp(jDateChooser3.getDate().getTime()).toString());
        System.out.println(new java.sql.Timestamp(Calendar.getInstance().getTime().getTime()).toString());
        int customerId = cs.addCustomer(customer);
        
//        createCustomerDialog.remove(this);

        jTextField27.setText("");
        jTextField4.setText("");
        jTextField26.setText("");
        jRadioButton3.setSelected(true);
        jDateChooser3.setDate(null);
        jLabel14.setIcon(null);
        
        
        
        jPanel64.removeAll();
        RingChartCustomer ringChartCustomer = new RingChartCustomer();
        HashMap<String, Float> customers = new HashMap<>();
        
        customers.put("New Customer", (float)totalNewCustomer);
        customers.put("Registered Customer", (float)totalRegisteredCustomer);
        
        ringChartCustomer.setData(customers);
        jPanel64.add(ringChartCustomer);
        
        
        
        
        jPanel226.removeAll();
        cs.getAllCustomer().forEach(e->{
            CustomerThumb cthumb = new CustomerThumb();
            cthumb.setCustomerData(e);
            if(e.getStatus().equals("Deleted")){
                cthumb.setVisible(false);
            }
            jPanel226.add(cthumb);
        });
        
        WrapLayout wrap = new WrapLayout();
        wrap.setAlignment(0);
        jPanel226.setLayout(wrap);
        
        jButton39.setVisible(false);
        
        FlatSVGIcon banicon = new FlatSVGIcon("img/icon/ban-solid.svg", 15, 15);
        banicon.setColorFilter(new FlatSVGIcon.ColorFilter(new Function<Color, Color>() {
            public Color apply(Color t) {
                return new Color(230, 76, 76);
            }
        }));
        jLabel309.setIcon(banicon);
        
//        createCustomerDialog.add(new CreateNewCustomerPanel());
        
        updateGraphics();
        
        if(isCustomerService){
            serviceCustomer = cs.getCustomerById(customerId);
            jTextField1.setText(serviceCustomer.getName());
        }
        
        createCustomerDialog.setVisible(false);
        
        
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        
        selectedFile = null;
        int option = chooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String filename = file.getAbsolutePath();
            BufferedImage bufferedImage = null;
            try {
                bufferedImage = ImageIO.read(new File(filename));
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            Image scaledImage = bufferedImage.getScaledInstance(-1, jLabel14.getHeight(), Image.SCALE_SMOOTH);

            ImageIcon image = new ImageIcon(scaledImage);

            jLabel14.setIcon(image);
            
            System.out.println(filename);
            
            System.out.println(getClass().getResource("/img/profile/" + filename));
            
            selectedFile = file;

        } else {
            System.out.println("Canceled");
        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
