/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos_timesquare.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;
import pos_timesquare.controller.CustomerService;
import pos_timesquare.controller.ProductService;
import pos_timesquare.controller.UserService;
import static pos_timesquare.view.MainFrame.darkRB;

/**
 *
 * @author Acer
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    
    public void ticketSearch(String value){
        ProductService ps = new ProductService();
        ps.getProductsByName(value).forEach(e -> {
            SearchResultThumb thumb = new SearchResultThumb();
            thumb.setData(e, 0);
            jPanel1.add(thumb);
        });
    }
    public void productSearch(String value){
        ProductService ps = new ProductService();
        ps.getProductsByName(value).forEach(e -> {
            SearchResultThumb thumb = new SearchResultThumb();
            thumb.setData(e, 1);
            jPanel1.add(thumb);
        });
    }
    
    public void personnelSearch(String value){
        UserService us = new UserService();
        
        us.getUserByName(value).forEach(e -> {
            SearchResultThumb thumb = new SearchResultThumb();
            thumb.setData(e, 2);
            jPanel1.add(thumb);
        });
        
    }
    
    public void customerSearch(String value){
        CustomerService cs = new CustomerService();
        
        cs.getAllCustomerByName(value).forEach(e -> {
            SearchResultThumb thumb = new SearchResultThumb();
            thumb.setData(e, 3);
            jPanel1.add(thumb);
        });
        
        if(!value.equals("")){
            if("customer #".contains(value)){
                cs.getAllCustomerByName("").forEach(e -> {
                    if(e.getName().equals("")){
                        SearchResultThumb thumb = new SearchResultThumb();
                        thumb.setData(e, 3);
                        jPanel1.add(thumb);
                    }
                });
            }else if(value.contains("customer #")){
                cs.getAllCustomerByName("").forEach(e -> {
                    if(e.getName().equals("")){
                        if(value.equals("customer #"+e.getId())){
                            SearchResultThumb thumb = new SearchResultThumb();
                            thumb.setData(e, 3);
                            jPanel1.add(thumb);
                        }
                    }
                });
            }
        }
        
    }
    
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        if(darkRB.isSelected()){
//            g2.setColor(new Color(38, 41, 48));
//        }else{
//            g2.setColor(new Color(255, 255, 255));
//        }
        g2.setColor(this.getBackground());
        g2.fillRoundRect(0, 0, this.getWidth()-1, this.getHeight()-1, 15, 15);

        if(darkRB.isSelected()){
            g2.setColor(new Color(55, 55, 65));
        }else{
            g2.setColor(new Color(225, 225, 225));
        }
        
        g2.drawRoundRect(0, 0, this.getWidth()-1, this.getHeight()-1, 15, 15);
    }
    
    public SearchPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 40));

        jLabel1.setText("Product Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        setOpaque(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setOpaque(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Search results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
