/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos_timesquare.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import javax.swing.JLayeredPane;
import pos_timesquare.controller.CustomerService;
import pos_timesquare.controller.ServiceTicketsService;
import pos_timesquare.model.Customer;
import pos_timesquare.model.ServiceTickets;
import static pos_timesquare.view.MainFrame.darkRB;
import static pos_timesquare.view.MainFrame.glassPanel;
import static pos_timesquare.view.MainFrame.jLayeredPane1;
import static pos_timesquare.view.MainFrame.selectCustomerPopupPanel;
import static pos_timesquare.view.MainFrame.updateGraphics;

/**
 *
 * @author Acer
 */
public class ServiceThumb2 extends javax.swing.JPanel {

    /**
     * Creates new form ServiceThumb2
     */
    
    boolean expanded = false;
    boolean isHover = false;
    
    boolean isRequiredAdmin = false;
    
    ServiceTickets serviceTicket = new ServiceTickets();
    
    Customer customer;
    
    public void setCustomer(Customer customer){
        this.customer = customer;
        jTextField12.setText(customer.getName());
        jLabel105.setText(customer.getName());
    }

    public ServiceTickets getServiceTicket() {
        return serviceTicket;
    }

    public void setServiceTicket(ServiceTickets serviceTicket) {
        this.serviceTicket = serviceTicket;
        CustomerService cs = new CustomerService();
        
        customer = cs.getCustomerById(serviceTicket.getCustomerId());
        
        if(customer.getName().replaceAll("\\s+","").equals("")){
            jLabel105.setText("Customer #" + customer.getId());
        }else{
        
            jLabel105.setText(customer.getName());
        }
        jLabel106.setText(serviceTicket.getWalkInDate().toString());
        jLabel108.setText("Order# " + String.valueOf(serviceTicket.getId()));
        
        if(serviceTicket.getStatus().equals("On Progress")){
            jLabel107.setForeground(new java.awt.Color(0, 204, 204));
            jComboBox5.setSelectedIndex(0);
        }else{
            jLabel107.setForeground(new java.awt.Color(0, 204, 104));
            jComboBox5.setSelectedIndex(1);
        }
        jLabel107.setText(serviceTicket.getStatus());
        
        
        //inputs
        jTextField12.setText(customer.getName());
        jDateChooser1.setDate(serviceTicket.getWalkInDate());
        jDateChooser2.setDate(serviceTicket.getEstimateFinish());
        jTextArea2.setText(serviceTicket.getDefects());
        jTextField13.setText(String.valueOf(serviceTicket.getPrice()));
        
        
        
        repaint();
        revalidate();
//        updateGraphics();
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        if(darkRB.isSelected()){
            g2.setColor(new Color(38, 41, 48));
            g2.fillRoundRect(0, 0, this.getWidth(), this.getHeight()-5, 20, 20);
            g2.setColor(new Color(58, 61, 68));
            g2.drawRoundRect(0, 0, this.getWidth()-1, this.getHeight()-6, 20, 20);
        }else{
            //            g2.setColor(new Color(245, 245, 245));
            g2.setColor(this.getBackground());
            g2.fillRoundRect(0, 0, this.getWidth(), this.getHeight()-5, 20, 20);
            g2.setColor(new Color(225, 225, 225));
            g2.drawRoundRect(0, 0, this.getWidth()-1, this.getHeight()-6, 20, 20);
        }
        
        if(isHover){
            if(!expanded){
                g2.setColor(new java.awt.Color(0, 144, 228));
                g2.drawRoundRect(0, 0, this.getWidth()-1, this.getHeight()-6, 20, 20);
            }
        }else{
            if(darkRB.isSelected()){
                g2.setColor(new Color(58, 61, 68));
                g2.drawRoundRect(0, 0, this.getWidth()-1, this.getHeight()-6, 20, 20);
            }else{
                g2.setColor(new Color(225, 225, 225));
                g2.drawRoundRect(0, 0, this.getWidth()-1, this.getHeight()-6, 20, 20);
            }
        }
        
    }
    
    void setRequiredAdmin(boolean data){
        isRequiredAdmin = data;
    }
    
    
    public ServiceThumb2() {
        initComponents();
        this.remove(serviceThumbExpand);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel114 = new javax.swing.JPanel();
        jPanel120 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel107 = new javax.swing.JLabel();
        jPanel121 = new javax.swing.JPanel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        serviceThumbExpand = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g.create();

                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                if(darkRB.isSelected()){
                    g2.setColor(new Color(58, 61, 68));
                    g2.drawLine(1, 1, this.getWidth()-2, 1);
                }else{
                    g2.setColor(new Color(225, 225, 225));
                    g2.drawLine(1, 1, this.getWidth()-2, 1);
                }
            }

        };
        jLabel118 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton18 = new javax.swing.JButton();
        jLabel119 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel122 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel123 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel114.setMaximumSize(new java.awt.Dimension(32767, 71));
        jPanel114.setMinimumSize(new java.awt.Dimension(100, 71));
        jPanel114.setOpaque(false);
        jPanel114.setPreferredSize(new java.awt.Dimension(400, 71));

        jPanel120.setOpaque(false);

        jButton17.setText("Set to Done");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel120Layout = new javax.swing.GroupLayout(jPanel120);
        jPanel120.setLayout(jPanel120Layout);
        jPanel120Layout.setHorizontalGroup(
            jPanel120Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel120Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addGap(15, 15, 15))
        );
        jPanel120Layout.setVerticalGroup(
            jPanel120Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel120Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel107.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(0, 204, 204));
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel107.setText("On Progress");

        jPanel121.setOpaque(false);
        jPanel121.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel121MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel121MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel121MouseExited(evt);
            }
        });

        jLabel105.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel105.setText("Paul Justine");

        jLabel106.setText("Oct 20 2022");

        jLabel108.setText("Service Ticket# 1");

        javax.swing.GroupLayout jPanel121Layout = new javax.swing.GroupLayout(jPanel121);
        jPanel121.setLayout(jPanel121Layout);
        jPanel121Layout.setHorizontalGroup(
            jPanel121Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel121Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel121Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel108, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel121Layout.setVerticalGroup(
            jPanel121Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel121Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel108)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel105)
                .addGap(0, 0, 0)
                .addComponent(jLabel106)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel114Layout = new javax.swing.GroupLayout(jPanel114);
        jPanel114.setLayout(jPanel114Layout);
        jPanel114Layout.setHorizontalGroup(
            jPanel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel114Layout.createSequentialGroup()
                .addComponent(jPanel121, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel120, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel114Layout.setVerticalGroup(
            jPanel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel120, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel107, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel121, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(jPanel114);

        serviceThumbExpand.setOpaque(false);
        serviceThumbExpand.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel118.setText("Defects");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane10.setViewportView(jTextArea2);

        jButton18.setText("Delete");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel119.setText("Walk-in Date");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On Progress", "Done" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel120.setText("Status");

        jLabel121.setText("Customer name");

        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField12.setFocusable(false);

        jLabel122.setText("Repair cost");

        jLabel123.setText("Estimated Finish");

        jButton19.setBackground(new java.awt.Color(0, 144, 228));
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Save changes");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jDateChooser1.setPreferredSize(null);

        jDateChooser2.setPreferredSize(null);

        jButton1.setText("Change Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout serviceThumbExpandLayout = new javax.swing.GroupLayout(serviceThumbExpand);
        serviceThumbExpand.setLayout(serviceThumbExpandLayout);
        serviceThumbExpandLayout.setHorizontalGroup(
            serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceThumbExpandLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10)
                    .addGroup(serviceThumbExpandLayout.createSequentialGroup()
                        .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel119))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel123)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(serviceThumbExpandLayout.createSequentialGroup()
                        .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel118)
                            .addComponent(jLabel121)
                            .addGroup(serviceThumbExpandLayout.createSequentialGroup()
                                .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel120))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel122)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(serviceThumbExpandLayout.createSequentialGroup()
                                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(serviceThumbExpandLayout.createSequentialGroup()
                        .addComponent(jTextField12)
                        .addGap(0, 0, 0)
                        .addComponent(jButton1)))
                .addGap(79, 79, 79))
        );
        serviceThumbExpandLayout.setVerticalGroup(
            serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceThumbExpandLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel121)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jTextField12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel119)
                    .addComponent(jLabel123))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel118)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serviceThumbExpandLayout.createSequentialGroup()
                        .addComponent(jLabel120)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel122))
                .addGap(18, 18, 18)
                .addGroup(serviceThumbExpandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        add(serviceThumbExpand);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        setToDone();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        if(!expanded){
            isHover = true;
//                    updateGraphics();
            repaint();
        }
        System.out.println("is hover");
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        if(!expanded){
            isHover = false;
//                    updateGraphics();
            repaint();
        }
    }//GEN-LAST:event_formMouseExited

    private void jPanel121MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel121MouseEntered
        // TODO add your handling code here:
        if(!expanded){
            isHover = true;
//                    updateGraphics();
            repaint();
        }
        System.out.println("is hover");
    }//GEN-LAST:event_jPanel121MouseEntered

    private void jPanel121MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel121MouseExited
        // TODO add your handling code here:
        if(!expanded){
            isHover = false;
//                    updateGraphics();
            repaint();
        }
    }//GEN-LAST:event_jPanel121MouseExited

    private void jPanel121MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel121MouseClicked
        // TODO add your handling code here:
        thumbClicked();
    }//GEN-LAST:event_jPanel121MouseClicked

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        removeThumb();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        updateThumb();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        CheckoutSelectCustomerPanel checkoutSelectCustomer = new CheckoutSelectCustomerPanel();
//        Point loc = jButton1.getLocationOnScreen();
//        checkoutSelectCustomer.setBounds((int)loc.getX(), (int)loc.getY(), 300, 270);
//        checkoutSelectCustomer.isProductCheckout(false);
//        jLayeredPane1.add(checkoutSelectCustomer, JLayeredPane.DRAG_LAYER);

//        glassPanel.setBounds(0, 0, this.getWidth(), this.getHeight());
        glassPanel.setVisible(true);

        CheckoutSelectCustomerPanel checkoutSelectCustomer = new CheckoutSelectCustomerPanel();
        Point loc = jButton1.getLocationOnScreen();

//            selectCustomerPopupPanel.setBounds((int)loc.getX(), (int)loc.getY(), 300, 270);
        selectCustomerPopupPanel.setBounds((int)loc.getX(), (int)loc.getY(), 300, 270);

        checkoutSelectCustomer.isProductCheckout(false);
        checkoutSelectCustomer.setForEditService(true);
//        checkoutSelectCustomer.setCallingComponent(jTextField12, jLabel105);
        checkoutSelectCustomer.setServiceTicketComp(this);
        checkoutSelectCustomer.setMinimumSize(new Dimension(300, 270));
        checkoutSelectCustomer.setPreferredSize(new Dimension(300, 270));

        selectCustomerPopupPanel.removeAll();
        selectCustomerPopupPanel.add(checkoutSelectCustomer);
        selectCustomerPopupPanel.setVisible(true);
        updateGraphics();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox5ActionPerformed


    public void setToDone(){
        ServiceTicketsService sts = new ServiceTicketsService();
        sts.setToDone(serviceTicket.getId());
        jLabel107.setForeground(new java.awt.Color(0, 204, 104));
        jLabel107.setText("Done");
        updateGraphics();
    }
    public void removeThumb(){
        ServiceTicketsService sts = new ServiceTicketsService();
        sts.deleteServiceTicketsById(serviceTicket.getId());
        System.out.println("delete ticket: " + serviceTicket.getId());
        this.getParent().remove(this);
    }
    public void thumbClicked(){
        if(isRequiredAdmin == false){
            System.out.println("Expand this panel");
            if(expanded){
                this.remove(serviceThumbExpand);
                expanded = false;
            }else{
                this.add(serviceThumbExpand);
                expanded = true;
            }
            updateGraphics();
        }else{
            if(MainFrame.user.getRole().equals("admin")){
                if(expanded){
                    this.remove(serviceThumbExpand);
                    expanded = false;
                }else{
                    this.add(serviceThumbExpand);
                    expanded = true;
                }
                updateGraphics();
            }
        }
    }
    
    public void updateThumb(){
        ServiceTicketsService sts = new ServiceTicketsService();
        sts.UpdateServiceTickets(
                serviceTicket.getId(), 
                customer.getId(), 
                jTextArea2.getText(), 
                Float.parseFloat(jTextField13.getText()), 
                new java.sql.Date(jDateChooser1.getDate().getTime()),
                new java.sql.Date(jDateChooser2.getDate().getTime()),
                jComboBox5.getSelectedItem().toString());
        
        if(jComboBox5.getSelectedItem().toString().equals("Done")){
            jLabel107.setForeground(new java.awt.Color(0, 204, 104));
        }else{
            jLabel107.setForeground(new java.awt.Color(0, 204, 204));
        }
        jLabel107.setText(jComboBox5.getSelectedItem().toString());
        jLabel105.setText(jTextField12.getText());
        jLabel106.setText(new java.sql.Date(jDateChooser1.getDate().getTime()).toString());

        this.remove(serviceThumbExpand);
        expanded = false;

        System.out.println("Update Success!!");
        System.out.println("ID: " + serviceTicket.getId());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JPanel jPanel114;
    private javax.swing.JPanel jPanel120;
    private javax.swing.JPanel jPanel121;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JPanel serviceThumbExpand;
    // End of variables declaration//GEN-END:variables
}
